server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      tracking-modes: cookie

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pictureboard
    username: root
    password: 11111111
  profiles:
    active: local
  messages:
    basename: messages,errors
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 197659776972-j9defpbc8r4emrm4uqufrs136p8clg38.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: Pm4TtJDob6ljZrP_sHbp
            client-secret: CUOiOaOvXF
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization_grant_type: authorization_code
            scope: name, email, profile_imag, gender, nickname
            client-name: Naver
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        #        show_sql: true
        format_sql: true
        use_sql_comment: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

file:
  profile: /Users/hipo/Desktop/pictureboard/src/main/resources/static/profile_img/
  picture: /Users/hipo/Desktop/pictureboard/src/main/resources/static/picture_img/